# Containers. Same as docker run
services:
  drupal: # Container's name. This is also DNS name inside network by default
    build: . # Build from the Dockerfile found in current directory
    image: custom-drupal # Rename the built image
    ports: # Same as -p in docker run
      - 8080:80
    volumes: # Same as -v in docker run
      # Check Docker Hub to know exposed volumes
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
  db:
    image: mariadb:11
    restart: always # Restart strategy if container crashed
    environment: # Same as -e in docker run
      MARIADB_ROOT_PASSWORD: pwd123
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: pwd123
    volumes:
      - db-data:/var/lib/mysql

volumes: # Same as docker volume create
  db-data:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
